# Generated by Django 3.1.3 on 2020-11-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=50, verbose_name='Video ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('video_link', models.URLField(max_length=300, verbose_name='Ссылка')),
                ('privacy_type', models.IntegerField(verbose_name='Тип доступа')),
                ('tags', models.JSONField(verbose_name='Тэги')),
                ('created_at', models.DateTimeField(verbose_name='Создано')),
                ('updated_at', models.DateTimeField(verbose_name='Обновлено')),
                ('plays', models.IntegerField(verbose_name='Количество проигрываний')),
            ],
        ),
    ]
