# Generated by Django 3.1.3 on 2020-11-22 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprout_tools', '0002_auto_20201120_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='folder_id',
            field=models.CharField(default='', max_length=20, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=1), verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='video',
            name='plays',
            field=models.IntegerField(default=0, verbose_name='Количество проигрываний'),
        ),
        migrations.AlterField(
            model_name='video',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=20, verbose_name='Video ID'),
        ),
    ]
