# Generated by Django 3.1.3 on 2020-11-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprout_tools', '0003_auto_20201122_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Video ID'),
        ),
    ]
