# Generated by Django 3.1.3 on 2021-01-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprout_tools', '0004_auto_20201122_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.CharField(max_length=15, unique=True, verbose_name='Folder ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('parent_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Parent')),
                ('created_at', models.DateTimeField(verbose_name='Создано')),
                ('updated_at', models.DateTimeField(verbose_name='Обновлено')),
            ],
        ),
    ]
