# Generated by Django 3.1.3 on 2021-01-07 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprout_tools', '0005_folder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'verbose_name': 'Folder', 'verbose_name_plural': 'Folders'},
        ),
        migrations.RemoveField(
            model_name='folder',
            name='parent_id',
        ),
    ]
